#!/bin/bash


# kill-session -t laravel-dev
# SAIL="./vendor/bin/sail"
# $SAIL down

SESSION="laravel-dev"
SAIL="./vendor/bin/sail"

echo "Limpando ambiente..."

# Fecha o Tmux primeiro para evitar que ele tente reiniciar algo
tmux kill-session -t $SESSION 2>/dev/null

# Derruba o Docker
$SAIL down

echo "Ambiente encerrado. Fechando terminal..."

# Fecha a janela do terminal atual
kill -9 $PPID